# Generated by Django 5.2.8 on 2025-11-22 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ticket_url', models.URLField()),
                ('image_url', models.URLField()),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=50)),
                ('venue', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('user_notes', models.TextField(blank=True)),
            ],
        ),
    ]
